language: csharp
solution: src/Ignite.Rules/Ignite.Rules.sln
mono:
  - alpha
before_install:
  - sudo apt-get install nunit-console
  - sudo apt-get update
before_script:
  - nuget restore src/Ignite.Rules/Ignite.Rules.sln
script:
  - xbuild /p:Configuration=Release src/Ignite.Rules/Ignite.Rules.sln /p:TargetFrameworkVersion="v4.5"
  - nunit-console src/Ignite.Rules/Ignite.Rules.Test/bin/Release/Ignite.Rules.Test.dll
