language: csharp
solution: src/Ignite.Rules/Ignite.Rules.sln
install:
  - nuget restore src/Ignite.Rules/Ignite.Rules.sln
script:
  - xbuild /p:Configuration=Release src/Ignite.Rules/Ignite.Rules.sln /p:TargetFrameworkVersion="v4.5"
  - ls ./packages
